// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp2QfGn2pkEUqPPozzy6KPDloYmYqomcU',
    appId: '1:850169121306:android:aaca72b011119b13171fa3',
    messagingSenderId: '850169121306',
    projectId: 'chat-apk-97e2a',
    storageBucket: 'chat-apk-97e2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUQyYsHXAF8Uz3NQcSVVtkoXY75VSgeEg',
    appId: '1:850169121306:ios:3e0c26cf14c6a124171fa3',
    messagingSenderId: '850169121306',
    projectId: 'chat-apk-97e2a',
    storageBucket: 'chat-apk-97e2a.appspot.com',
    androidClientId: '850169121306-laqtjep3s9rkkn2bqf2tsg56p0nqk6ic.apps.googleusercontent.com',
    iosClientId: '850169121306-103qqk33pt9i63bo1n6f80208faglg6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApk',
  );
}
